name: .NET Onboarding

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.7.21379.14
    - name: Restore dependencies
      run: dotnet restore src/Saas.Onboarding/Saas.Onboarding.sln
    - name: Build
      run: dotnet build src/Saas.Onboarding/Saas.Onboarding.sln --no-restore
    - name: Test
      run: dotnet test src/Saas.Onboarding/Saas.Onboarding.sln --no-build --verbosity normal
